LogFile: ./log/modelServer.log
LogLevel: DEBUG

Database: root:admin123@/outside

RedisAddr: 127.0.0.1:6379
RedisPwd: 
RedisTimeOut: 60

#接收DeviceServer上报的状态
RecvAmqpURI: amqp://rabbit:rabbitsuanier@127.0.0.1:5672/server-ctrl 
RecvRoutKey:  result-report
RecvExchangeName: result-report-exechange
RecvChanReadQName: result-report-recv-queue
####################

PushblishAmqpURI: amqp://rabbit:rabbitsuanier@127.0.0.1:5672/server-ctrl  
PushblisRoutKey:  door-ctrl-routkey 
PushExchangeName: door-ctrl-exchange
####################
