LogFile: ./log/modelServer.log
LogLevel: DEBUG

Database: root:suanier@/vis_db_sa

RedisAddr: 127.0.0.1:9000
RedisPwd: admin123
RedisTimeOut: 60

#接收DeviceServer上报的状态
RecvAmqpURI: amqp://rabbit:rabbitsuanier@192.168.1.6:5672/server-ctrl 
RecvExchangeName: door-ctrl-exechange
RecvChanReadQName: door-ctrl-recv
RecvRoutKey:  door-ctrl-routkey
####################

PushblishAmqpURI: amqp://rabbit:rabbitsuanier@192.168.1.6:5672/server-ctrl  
PushblisRoutKey:  door-ctrl-routkey 
####################