LogFile: ./log/modelServer.log
LogLevel: DEBUG

Database: root:suanier@/vis_db_sa

RedisAddr: 127.0.0.1:9000
RedisPwd: admin123
RedisTimeOut: 60

RecvAmqpURI: amqp://rabbit:rabbitsuanier@192.168.1.6:5672/server-ctrl 
RecvExchangeName: 
RecvChanReadQName: door-ctrl-recv
RecvChanWriteQName: 
RecvRoutKey:  door-ctrl-routkey
####################

AmqpURI: amqp://rabbit:rabbitsuanier@192.168.1.6:5672/server-ctrl  
ChanWriteQName: result-report 
####################